from pathlib import Path
from typing import List

from multi.managed_blocks import (
    ManagedBlock,
    get_managed_block_lines,
    has_managed_block,
    replace_managed_block,
)
from multi.paths import Paths
from multi.repos import load_repos

REPO_DIRECTORIES_BLOCK = ManagedBlock("repo-directories")
SEARCHABLE_REPOS_BLOCK = ManagedBlock("search-inside-gitignored-repos")
GENERATED_FILES_BLOCK = ManagedBlock("generated-files")


class IgnoreFile:
    def __init__(self, path: Path, block: ManagedBlock):
        self.path = path
        self.block = block

    @property
    def existing_lines(self) -> List[str]:
        if not self.path.exists():
            return []
        return self.path.read_text(encoding="utf-8").splitlines()

    def set_managed_lines(self, lines: List[str]) -> None:
        replace_managed_block(self.path, self.block, lines)

    def remove_managed_lines(self, lines: List[str]) -> None:
        if not self.path.exists():
            return

        existing_text = self.path.read_text(encoding="utf-8")
        if has_managed_block(existing_text, self.block):
            existing_lines = get_managed_block_lines(existing_text, self.block)
            next_lines = [line for line in existing_lines if line not in set(lines)]
            replace_managed_block(self.path, self.block, next_lines)
            return

        updated_lines = [
            line
            for line in existing_text.splitlines()
            if line not in set(lines)
        ]
        next_text = ""
        if updated_lines:
            next_text = "\n".join(updated_lines).rstrip("\n") + "\n"
        if next_text:
            self.path.write_text(next_text, encoding="utf-8")
        else:
            self.path.unlink()


def _repo_entries(paths: Paths) -> List[str]:
    entries: List[str] = [
        "# multi avoids git submodules; each entry has both forms: trailing slash matches directories, bare name matches symlinks/aliases.",
    ]
    for repo in load_repos(paths=paths):
        entries.append(f"{repo.name}/")
        entries.append(repo.name)
    return entries


def _search_entries(paths: Paths) -> List[str]:
    entries: List[str] = [
        "# Allow us to search inside these gitignored directories",
    ]
    for repo in load_repos(paths=paths):
        entries.append(f"!{repo.name}/")
        entries.append(f"!{repo.name}")
    return entries


def _subrepo_generated_entries(repo_path: Path) -> List[str]:
    entries = ["# These files are generated by multi.", "CLAUDE.md", "AGENTS.md"]
    repo_vscode_dir = repo_path / ".vscode"
    if (
        (repo_vscode_dir / "settings.shared.json").exists()
        or (repo_vscode_dir / "settings.local.json").exists()
    ):
        entries.append(".vscode/settings.json")
    return entries


def clear_subrepo_generated_file_block(repo_path: Path) -> None:
    IgnoreFile(repo_path / ".gitignore", GENERATED_FILES_BLOCK).set_managed_lines([])


def update_gitignore_with_repos(paths: Paths):
    gitignore = IgnoreFile(paths.gitignore_path, REPO_DIRECTORIES_BLOCK)
    if paths.settings.is_monorepo():
        gitignore.set_managed_lines([])
        return
    gitignore.set_managed_lines(_repo_entries(paths))


def update_ignore_with_repos(paths: Paths):
    vscode_ignore = IgnoreFile(paths.vscode_ignore_path, SEARCHABLE_REPOS_BLOCK)
    if paths.settings.is_monorepo():
        vscode_ignore.set_managed_lines([])
        return
    vscode_ignore.set_managed_lines(_search_entries(paths))


def remove_gitignore_entries_for_repos(paths: Paths, repo_names: List[str]) -> None:
    if not repo_names:
        return

    entries = []
    for repo_name in repo_names:
        entries.append(f"{repo_name}/")
        entries.append(repo_name)

    IgnoreFile(paths.gitignore_path, REPO_DIRECTORIES_BLOCK).remove_managed_lines(
        entries
    )


def remove_ignore_entries_for_repos(paths: Paths, repo_names: List[str]) -> None:
    if not repo_names:
        return

    entries = []
    for repo_name in repo_names:
        entries.append(f"!{repo_name}/")
        entries.append(f"!{repo_name}")

    IgnoreFile(paths.vscode_ignore_path, SEARCHABLE_REPOS_BLOCK).remove_managed_lines(
        entries
    )


def update_gitignore_with_generated_files(paths: Paths):
    root_generated_entries = [
        "# These files are generated by multi.",
        ".vscode/settings.json",
        ".vscode/tasks.json",
        ".vscode/launch.json",
        ".vscode/extensions.json",
        "CLAUDE.md",
        "AGENTS.md",
    ]
    IgnoreFile(paths.gitignore_path, GENERATED_FILES_BLOCK).set_managed_lines(
        root_generated_entries
    )

    if paths.settings.is_monorepo() or not paths.settings.get("repos"):
        return

    repos = load_repos(paths=paths)
    for repo in repos:
        repo_git_dir = repo.path / ".git"
        if not repo_git_dir.exists():
            continue

        if not repo.manage_gitignore:
            clear_subrepo_generated_file_block(repo.path)
            continue

        IgnoreFile(repo.path / ".gitignore", GENERATED_FILES_BLOCK).set_managed_lines(
            _subrepo_generated_entries(repo.path)
        )
