import logging
from pathlib import Path
from typing import Any, Dict, List

import click

from multi.paths import Paths
from multi.repos import Repository, load_repos
from multi.sync_vscode_helpers import VSCodeFileMerger, deep_merge
from multi.utils import (
    soft_read_json_file,
    write_jsonc_file,
)

LOCAL_GENERATED_SETTINGS_HEADER = (
    "This file is generated by multi from settings.shared.json and/or settings.local.json. Do not edit directly."
)

logger = logging.getLogger(__name__)


def _load_repo_companion_settings(repo_path: Path) -> tuple[bool, Dict[str, Any]]:
    vscode_dir = repo_path / ".vscode"
    shared_settings_path = vscode_dir / "settings.shared.json"
    local_settings_path = vscode_dir / "settings.local.json"

    has_companion_settings = (
        shared_settings_path.exists() or local_settings_path.exists()
    )
    merged_settings: Dict[str, Any] = {}

    if shared_settings_path.exists():
        merged_settings = deep_merge(
            merged_settings,
            soft_read_json_file(shared_settings_path),
        )

    if local_settings_path.exists():
        merged_settings = deep_merge(
            merged_settings,
            soft_read_json_file(local_settings_path),
        )

    return has_companion_settings, merged_settings


class SettingsFileMerger(VSCodeFileMerger):
    def _get_destination_json_path(self) -> Path:
        return self.paths.vscode_settings_path

    def _get_source_json_path(self, repo_path: Path) -> Path:
        return self.paths.get_vscode_config_dir(repo_path) / "settings.json"

    def _get_skip_keys(self, repo: Repository) -> List[str] | None:
        """Return the list of settings keys to skip during merge."""
        return self.paths.settings["vscode"].get("skipSettings", [])

    def _merge_repo_json(
        self,
        merged_json: Dict[str, Any],
        repo_json: Dict[str, Any],
        repo: Repository,
        source_json_path: Path,
    ) -> Dict[str, Any]:
        """
        Regenerate the repo's settings.json from companion settings files when present.
        If a repo has settings.shared.json or settings.local.json, those files become
        the complete source of truth for the generated settings.json.
        Also applies settingsOverrides from the repo's multi.json config if present.
        """
        repo_settings_path = (
            self.paths.get_vscode_config_dir(repo.path) / "settings.json"
        )
        raw_repo_settings = (
            repo_settings_path.read_text(encoding="utf-8")
            if repo_settings_path.exists()
            else ""
        )
        has_companion_settings, companion_settings = _load_repo_companion_settings(
            repo.path
        )

        if has_companion_settings:
            repo_json = companion_settings

            write_jsonc_file(
                repo_settings_path,
                repo_json,
                header_comment=LOCAL_GENERATED_SETTINGS_HEADER,
            )
        elif raw_repo_settings.startswith(f"// {LOCAL_GENERATED_SETTINGS_HEADER}"):
            write_jsonc_file(repo_settings_path, repo_json)

        # Apply settingsOverrides from the repo's multi.json config if present
        vscode_config = getattr(repo, "vscode", None)
        if isinstance(vscode_config, dict):
            settings_overrides = vscode_config.get("settingsOverrides")
            if settings_overrides:
                logger.debug(f"Applying settingsOverrides for {repo.name}")
                repo_json = deep_merge(repo_json, settings_overrides)

        return super()._merge_repo_json(merged_json, repo_json, repo, source_json_path)

    def _post_process_json(self, merged_json: Dict[str, Any]) -> Dict[str, Any]:
        # Merge in settings.shared.json
        shared_settings_path = self.paths.vscode_settings_shared_path
        if shared_settings_path.exists():
            shared_settings = soft_read_json_file(shared_settings_path)
            merged_json = deep_merge(merged_json, shared_settings)
        else:
            logger.debug(
                f"Shared settings file not found at {shared_settings_path.name}, skipping."
            )

        local_settings_path = self.paths.vscode_settings_local_path
        if local_settings_path.exists():
            local_settings = soft_read_json_file(local_settings_path)
            merged_json = deep_merge(merged_json, local_settings)
        else:
            logger.debug(
                f"Local settings file not found at {local_settings_path.name}, skipping."
            )

        # Add Python paths for autocomplete
        repos = load_repos(self.paths)
        python_paths_to_add = [repo.name for repo in repos if repo.is_python]
        if python_paths_to_add:
            logger.info("Adding Python paths for autocomplete")
            current_extra_paths = merged_json.setdefault(
                "python.autoComplete.extraPaths", []
            )

            for path_val in python_paths_to_add:
                if path_val not in current_extra_paths:
                    current_extra_paths.append(path_val)
        return merged_json


def merge_settings_json(root_dir: Path) -> None:
    paths = Paths(root_dir)
    merger = SettingsFileMerger(paths=paths)
    merger.merge()
    from multi.ignore_files import update_gitignore_with_generated_files

    update_gitignore_with_generated_files(paths=paths)


@click.command(name="settings")
def merge_settings_cmd():
    """Merge settings.json files from all repositories into the root .vscode directory.

    This command will:
    1. Merge VSCode settings from all repos using the new merger class.
    2. Apply shared/local settings from settings.shared.json and settings.local.json.
    3. Configure Python autocomplete paths.
    """
    logger.info("Merging settings.json files from all repositories...")
    merge_settings_json(root_dir=Path.cwd())
