import json

from multi.sync_vscode_settings import merge_settings_json
from multi.utils import soft_read_json_file


def test_merge_settings_files(setup_git_repos):
    root_repo_path, sub_repo_dirs = setup_git_repos
    repo0_path = sub_repo_dirs[0]  # repo0
    repo1_path = sub_repo_dirs[1]  # repo1

    # --- Make repo0 a Python project by adding pyproject.toml ---
    pyproject_content = """[tool.poetry]
name = "repo0"
version = "0.1.0"
description = ""
authors = ["Test User <test@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
"""
    (repo0_path / "pyproject.toml").write_text(pyproject_content)

    # --- Create .vscode dirs ---
    (root_repo_path / ".vscode").mkdir(exist_ok=True)
    (repo0_path / ".vscode").mkdir(exist_ok=True)
    (repo1_path / ".vscode").mkdir(exist_ok=True)

    # --- Repo0 settings.json ---
    repo0_settings_content = {
        "python.pythonPath": "${workspaceFolder}/.venv/bin/python",
        "editor.formatOnSave": True,
        "files.exclude": {"**/.git": True, "**/__pycache__": True},
    }
    (repo0_path / ".vscode" / "settings.json").write_text(
        json.dumps(repo0_settings_content)
    )

    # --- Repo1 settings.json ---
    repo1_settings_content = {
        "editor.tabSize": 2,
        "files.exclude": {"**/.DS_Store": True},
        "toBeSkipped": "repo1Value",
        "anotherKey": "repo1Specific",
    }
    (repo1_path / ".vscode" / "settings.json").write_text(
        json.dumps(repo1_settings_content)
    )

    # --- Root .vscode/settings.shared.json ---
    shared_settings_content = {
        "editor.rulers": [80, 120],
        "search.exclude": {"**/node_modules": True, "**/bower_components": True},
    }
    (root_repo_path / ".vscode" / "settings.shared.json").write_text(
        json.dumps(shared_settings_content)
    )
    (root_repo_path / ".vscode" / "settings.local.json").write_text(
        json.dumps(
            {
                "editor.tabSize": 4,
                "terminal.integrated.fontSize": 14,
            }
        )
    )

    # Add skipSettings to multi.json
    multi_json_path = root_repo_path / "multi.json"
    with open(multi_json_path, "r") as f:
        multi_json = json.load(f)
    multi_json["vscode"] = {"skipSettings": ["toBeSkipped"]}
    with open(multi_json_path, "w") as f:
        json.dump(multi_json, f, indent=2)

    # Call the merge function
    merge_settings_json(root_repo_path)

    # Assertions
    merged_file_path = root_repo_path / ".vscode" / "settings.json"
    assert merged_file_path.exists()

    merged_data = soft_read_json_file(merged_file_path)

    assert (
        merged_data.get("python.pythonPath")
        == "${workspaceFolder}/repo0/.venv/bin/python"
    )
    assert merged_data.get("editor.formatOnSave") is True
    assert merged_data.get("editor.tabSize") == 4
    assert merged_data.get("anotherKey") == "repo1Specific"
    assert "toBeSkipped" not in merged_data
    assert merged_data["files.exclude"]["**/.git"] is True
    assert merged_data["files.exclude"]["**/__pycache__"] is True
    assert merged_data["files.exclude"]["**/.DS_Store"] is True
    assert merged_data["editor.rulers"] == [80, 120]
    assert merged_data["terminal.integrated.fontSize"] == 14
    assert merged_data["search.exclude"]["**/node_modules"] is True
    assert "python.autoComplete.extraPaths" in merged_data
    assert "repo0" in merged_data["python.autoComplete.extraPaths"]
    assert "repo1" not in merged_data["python.autoComplete.extraPaths"]
    assert len(merged_data["python.autoComplete.extraPaths"]) == 1


def test_repo_settings_shared_json_creates_generated_jsonc_and_gitignore(setup_git_repos):
    root_repo_path, sub_repo_dirs = setup_git_repos
    repo0_path = sub_repo_dirs[0]

    (repo0_path / ".vscode").mkdir(exist_ok=True)
    (repo0_path / ".vscode" / "settings.json").write_text(
        json.dumps(
            {
                "editor.tabSize": 2,
                "files.exclude": {"**/.DS_Store": True},
            }
        ),
        encoding="utf-8",
    )
    (repo0_path / ".vscode" / "settings.shared.json").write_text(
        json.dumps(
            {
                "editor.rulers": [80, 120],
            }
        ),
        encoding="utf-8",
    )

    merge_settings_json(root_repo_path)

    repo_settings_path = repo0_path / ".vscode" / "settings.json"
    repo_settings_text = repo_settings_path.read_text(encoding="utf-8")
    assert (
        "// This file is generated by multi from settings.shared.json and/or settings.local.json. Do not edit directly."
        in repo_settings_text
    )
    assert '"editor.rulers": [' in repo_settings_text
    assert '"editor.tabSize": 2' not in repo_settings_text
    assert '"files.exclude"' not in repo_settings_text
    assert "BEGIN multi-managed: shared-settings" not in repo_settings_text

    repo_gitignore_text = (repo0_path / ".gitignore").read_text(encoding="utf-8")
    assert ".vscode/settings.json" in repo_gitignore_text

    merged_root_settings = soft_read_json_file(root_repo_path / ".vscode" / "settings.json")
    assert merged_root_settings["editor.rulers"] == [80, 120]
    assert "editor.tabSize" not in merged_root_settings


def test_repo_settings_shared_json_rebuilds_generated_settings_from_scratch(
    setup_git_repos,
):
    root_repo_path, sub_repo_dirs = setup_git_repos
    repo0_path = sub_repo_dirs[0]

    (repo0_path / ".vscode").mkdir(exist_ok=True)
    (repo0_path / ".vscode" / "settings.json").write_text(
        json.dumps(
            {
                "stale.setting": "remove-me",
            }
        ),
        encoding="utf-8",
    )
    (repo0_path / ".vscode" / "settings.shared.json").write_text(
        json.dumps(
            {
                "editor.rulers": [80, 120],
            }
        ),
        encoding="utf-8",
    )

    merge_settings_json(root_repo_path)

    (repo0_path / ".vscode" / "settings.shared.json").write_text(
        json.dumps(
            {
                "editor.rulers": [100],
            }
        ),
        encoding="utf-8",
    )

    merge_settings_json(root_repo_path)

    repo_settings = soft_read_json_file(repo0_path / ".vscode" / "settings.json")
    assert repo_settings == {"editor.rulers": [100]}

    merged_root_settings = soft_read_json_file(root_repo_path / ".vscode" / "settings.json")
    assert merged_root_settings["editor.rulers"] == [100]
    assert "stale.setting" not in merged_root_settings


def test_repo_settings_local_json_also_creates_generated_jsonc_and_gitignore(
    setup_git_repos,
):
    root_repo_path, sub_repo_dirs = setup_git_repos
    repo0_path = sub_repo_dirs[0]

    (repo0_path / ".vscode").mkdir(exist_ok=True)
    (repo0_path / ".vscode" / "settings.json").write_text(
        json.dumps(
            {
                "editor.tabSize": 2,
            }
        ),
        encoding="utf-8",
    )
    (repo0_path / ".vscode" / "settings.local.json").write_text(
        json.dumps(
            {
                "editor.rulers": [100],
            }
        ),
        encoding="utf-8",
    )

    merge_settings_json(root_repo_path)

    repo_settings_path = repo0_path / ".vscode" / "settings.json"
    repo_settings_text = repo_settings_path.read_text(encoding="utf-8")
    assert (
        "// This file is generated by multi from settings.shared.json and/or settings.local.json. Do not edit directly."
        in repo_settings_text
    )
    assert '"editor.rulers": [' in repo_settings_text
    assert '"editor.tabSize": 2' not in repo_settings_text

    repo_gitignore_text = (repo0_path / ".gitignore").read_text(encoding="utf-8")
    assert ".vscode/settings.json" in repo_gitignore_text
    assert "settings.local.json" not in repo_gitignore_text

    merged_root_settings = soft_read_json_file(root_repo_path / ".vscode" / "settings.json")
    assert merged_root_settings["editor.rulers"] == [100]
    assert "editor.tabSize" not in merged_root_settings
