import json

from multi.ignore_files import (
    GENERATED_FILES_BLOCK,
    REPO_DIRECTORIES_BLOCK,
    SEARCHABLE_REPOS_BLOCK,
    IgnoreFile,
    clear_subrepo_generated_file_block,
    remove_gitignore_entries_for_repos,
    remove_ignore_entries_for_repos,
    update_gitignore_with_generated_files,
    update_gitignore_with_repos,
    update_ignore_with_repos,
)
from multi.paths import Paths


def test_set_managed_lines_preserves_existing_content(tmp_path):
    ignore_path = tmp_path / ".gitignore"
    ignore_path.write_text("# Existing\nkeep-me\n", encoding="utf-8")

    ignore_file = IgnoreFile(ignore_path, REPO_DIRECTORIES_BLOCK)
    ignore_file.set_managed_lines(["repo-a/", "repo-a"])

    content = ignore_path.read_text(encoding="utf-8")
    assert "# Existing\nkeep-me\n" in content
    assert REPO_DIRECTORIES_BLOCK.begin_marker in content
    assert "repo-a/" in content
    assert "repo-a" in content
    assert REPO_DIRECTORIES_BLOCK.end_marker in content


def test_update_repo_and_search_blocks_use_managed_markers(tmp_path):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / "multi.json").write_text(
        json.dumps(
            {
                "repos": [
                    {"url": "https://github.com/test/repo-a"},
                    {"url": "https://github.com/test/repo-b"},
                ]
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    paths = Paths(workspace)
    update_gitignore_with_repos(paths)
    update_ignore_with_repos(paths)

    gitignore = (workspace / ".gitignore").read_text(encoding="utf-8")
    assert REPO_DIRECTORIES_BLOCK.begin_marker in gitignore
    assert (
        "# multi avoids git submodules; each entry has both forms: trailing slash matches directories, bare name matches symlinks/aliases."
        in gitignore
    )
    assert "repo-a/" in gitignore
    assert "repo-b" in gitignore
    assert REPO_DIRECTORIES_BLOCK.end_marker in gitignore

    ignore = (workspace / ".ignore").read_text(encoding="utf-8")
    assert SEARCHABLE_REPOS_BLOCK.begin_marker in ignore
    assert "# Allow us to search inside these gitignored directories" in ignore
    assert "!repo-a/" in ignore
    assert "!repo-b" in ignore
    assert SEARCHABLE_REPOS_BLOCK.end_marker in ignore


def test_update_gitignore_with_generated_files_updates_root_and_subrepos(tmp_path):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / "multi.json").write_text(
        json.dumps(
            {
                "repos": [
                    {"url": "https://github.com/test/repo-a"},
                    {"url": "https://github.com/test/repo-b"},
                ]
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    repo_a = workspace / "repo-a"
    repo_b = workspace / "repo-b"
    (repo_a / ".git").mkdir(parents=True)
    (repo_b / ".git").mkdir(parents=True)
    (repo_a / ".vscode").mkdir()
    (repo_a / ".vscode" / "settings.shared.json").write_text("{}", encoding="utf-8")

    update_gitignore_with_generated_files(Paths(workspace))

    root_gitignore = (workspace / ".gitignore").read_text(encoding="utf-8")
    assert GENERATED_FILES_BLOCK.begin_marker in root_gitignore
    assert "# These files are generated by multi." in root_gitignore
    assert ".vscode/settings.json" in root_gitignore
    assert ".vscode/tasks.json" in root_gitignore
    assert "CLAUDE.md" in root_gitignore
    assert GENERATED_FILES_BLOCK.end_marker in root_gitignore

    repo_a_gitignore = (repo_a / ".gitignore").read_text(encoding="utf-8")
    assert GENERATED_FILES_BLOCK.begin_marker in repo_a_gitignore
    assert "# These files are generated by multi." in repo_a_gitignore
    assert "CLAUDE.md" in repo_a_gitignore
    assert "AGENTS.md" in repo_a_gitignore
    assert ".vscode/settings.json" in repo_a_gitignore

    repo_b_gitignore = (repo_b / ".gitignore").read_text(encoding="utf-8")
    assert GENERATED_FILES_BLOCK.begin_marker in repo_b_gitignore
    assert "# These files are generated by multi." in repo_b_gitignore
    assert "CLAUDE.md" in repo_b_gitignore
    assert "AGENTS.md" in repo_b_gitignore
    assert ".vscode/settings.json" not in repo_b_gitignore


def test_update_gitignore_with_generated_files_skips_non_git_subrepo(tmp_path):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / "multi.json").write_text(
        json.dumps(
            {
                "repos": [
                    {"url": "https://github.com/test/repo-a"},
                    {"url": "https://github.com/test/repo-b"},
                ]
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    repo_a = workspace / "repo-a"
    repo_b = workspace / "repo-b"
    (repo_a / ".git").mkdir(parents=True)
    repo_b.mkdir(parents=True)

    update_gitignore_with_generated_files(Paths(workspace))

    assert (repo_a / ".gitignore").exists()
    assert not (repo_b / ".gitignore").exists()


def test_update_gitignore_with_generated_files_respects_manage_gitignore_false(
    tmp_path,
):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / "multi.json").write_text(
        json.dumps(
            {
                "repos": [
                    {"url": "https://github.com/test/repo-a"},
                    {
                        "url": "https://github.com/test/repo-b",
                        "manageGitignore": False,
                    },
                ]
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    repo_a = workspace / "repo-a"
    repo_b = workspace / "repo-b"
    (repo_a / ".git").mkdir(parents=True)
    (repo_b / ".git").mkdir(parents=True)

    update_gitignore_with_generated_files(Paths(workspace))

    root_gitignore = (workspace / ".gitignore").read_text(encoding="utf-8")
    assert GENERATED_FILES_BLOCK.begin_marker in root_gitignore
    assert (repo_a / ".gitignore").exists()
    assert not (repo_b / ".gitignore").exists()


def test_update_gitignore_with_generated_files_clears_disabled_subrepo_block(
    tmp_path,
):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / "multi.json").write_text(
        json.dumps(
            {
                "repos": [
                    {
                        "url": "https://github.com/test/repo-a",
                        "manageGitignore": False,
                    },
                ]
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    repo_a = workspace / "repo-a"
    (repo_a / ".git").mkdir(parents=True)
    (repo_a / ".gitignore").write_text(
        "\n".join(
            [
                "keep-me",
                "",
                GENERATED_FILES_BLOCK.begin_marker,
                "# These files are generated by multi.",
                "CLAUDE.md",
                "AGENTS.md",
                GENERATED_FILES_BLOCK.end_marker,
                "",
            ]
        ),
        encoding="utf-8",
    )

    update_gitignore_with_generated_files(Paths(workspace))

    assert (repo_a / ".gitignore").read_text(encoding="utf-8") == "keep-me\n"


def test_remove_repo_entries_from_ignore_files_removes_only_managed_lines(tmp_path):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    (workspace / ".gitignore").write_text(
        "\n".join(
            [
                "keep/",
                "",
                REPO_DIRECTORIES_BLOCK.begin_marker,
                "repo-a/",
                "repo-a",
                "repo-b/",
                "repo-b",
                REPO_DIRECTORIES_BLOCK.end_marker,
                "",
            ]
        ),
        encoding="utf-8",
    )
    (workspace / ".ignore").write_text(
        "\n".join(
            [
                "!keep/",
                "",
                SEARCHABLE_REPOS_BLOCK.begin_marker,
                "!repo-a/",
                "!repo-a",
                "!repo-b/",
                "!repo-b",
                SEARCHABLE_REPOS_BLOCK.end_marker,
                "",
            ]
        ),
        encoding="utf-8",
    )

    paths = Paths.__new__(Paths)
    paths.root_dir = workspace

    remove_gitignore_entries_for_repos(paths, ["repo-a"])
    remove_ignore_entries_for_repos(paths, ["repo-a"])

    gitignore = (workspace / ".gitignore").read_text(encoding="utf-8")
    assert "keep/" in gitignore
    assert "repo-a/" not in gitignore
    assert "repo-b/" in gitignore
    assert REPO_DIRECTORIES_BLOCK.begin_marker in gitignore

    ignore = (workspace / ".ignore").read_text(encoding="utf-8")
    assert "!keep/" in ignore
    assert "!repo-a/" not in ignore
    assert "!repo-b/" in ignore
    assert SEARCHABLE_REPOS_BLOCK.begin_marker in ignore


def test_clear_subrepo_generated_file_block_removes_only_managed_block(tmp_path):
    repo_path = tmp_path / "repo-a"
    repo_path.mkdir()
    gitignore_path = repo_path / ".gitignore"
    gitignore_path.write_text(
        "\n".join(
            [
                "keep-me",
                "",
                GENERATED_FILES_BLOCK.begin_marker,
                "CLAUDE.md",
                "AGENTS.md",
                GENERATED_FILES_BLOCK.end_marker,
                "",
            ]
        ),
        encoding="utf-8",
    )

    clear_subrepo_generated_file_block(repo_path)

    assert gitignore_path.read_text(encoding="utf-8") == "keep-me\n"
